import { uiLanguage } from '../utils/presentation'

const copies = {
  en: {
    entry: {
      eyebrow: 'Work-first planning',
      title: 'Build your operating plan',
      description: 'Import company planning data or use the existing sample dataset to understand the workflow. Work is reviewed before people, schedules, or final numbers.',
      create: 'Create new plan',
      sample: 'Use sample data',
    },
    planning: {
      eyebrow: 'Step 1 · Planning data',
      title: 'Create or load planning data',
      description: 'Use a JSON file that follows the supported NexaWorks dataset schema, or start safely with the unchanged sample dataset.',
      upload: 'Load a planning JSON file',
      uploadHelp: 'The file is validated against the existing schema. Loading data does not analyze work or generate a plan.',
      choose: 'Choose JSON file',
      sample: 'Use sample data',
      reviewing: 'Validating planning data…',
      loaded: 'Planning data is ready for review',
      sampleSource: 'Existing sample dataset',
      uploadedSource: 'Uploaded planning dataset',
      horizon: 'Planning horizon',
      workItems: 'Work items',
      people: 'People',
      capacity: 'Available capacity',
      commercial: 'Commercial options',
      resources: 'Shared resources',
      effects: 'Portfolio effects',
      startingCash: 'Starting cash',
      buffer: 'Minimum cash buffer',
      reviewWork: 'Review work items',
      startOver: 'Start over',
      invalid: 'This file could not be loaded as supported planning data.',
    },
    work: {
      eyebrow: 'Steps 2–3 · Work portfolio',
      title: 'Review the work before assigning people',
      description: 'Understand commitments, effort, deadlines, customers, and dependencies before asking the system for a recommendation.',
      all: 'All work',
      mandatory: 'Mandatory',
      commercial: 'Commercial',
      other: 'Other work',
      mandatoryLabel: 'Mandatory commitment',
      optionalLabel: 'Optional work',
      hours: 'Required effort',
      deadline: 'Deadline',
      customer: 'Customer',
      dependencies: 'Dependencies',
      none: 'None',
      notAnalyzed: 'Not analyzed yet',
      analyze: 'Analyze portfolio',
      analyzing: 'Analyzing portfolio…',
      analysisReady: 'Portfolio analysis is ready',
      analysisExplain: 'Priority describes business importance. It does not define execution order.',
      dependencyExample: '{{work}} is important, but prerequisite work must be completed first.',
      priority: 'Priority',
      veryHigh: 'Very high',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      feasibility: 'Feasibility',
      feasible: 'Can be performed',
      blocked: 'Blocked until prerequisites are completed',
      infeasible: 'Cannot be performed under current assumptions',
      atRisk: 'At risk',
      keyReasons: 'Key reasons',
      rawEvidence: 'Analysis evidence',
      generate: 'Generate recommended plan',
      generating: 'Generating recommended plan…',
      planReady: 'Recommended plan generated',
      openPlan: 'Review execution plan',
    },
    gate: {
      noDataTitle: 'Planning data is required first',
      noDataBody: 'Create a plan or load the sample dataset before reviewing this step.',
      goPlanning: 'Go to Planning',
      analysisTitle: 'Analyze the work portfolio first',
      analysisBody: 'Review the available work and explicitly run portfolio analysis before generating a plan.',
      goWork: 'Review work items',
      planTitle: 'No recommended plan has been generated',
      planBody: 'Generate the plan from the analyzed work portfolio before reviewing assignments, cash, scenarios, or the executive summary.',
      generatePlan: 'Generate recommended plan',
      sampleOnlyTitle: 'Scenarios currently use the sample baseline',
      sampleOnlyBody: 'This uploaded dataset remains isolated. Start a sample-data workflow to use the existing scenario engine.',
    },
    progress: {
      data: 'Planning data',
      work: 'Work review',
      analysis: 'Analysis',
      plan: 'Recommended plan',
      complete: 'Complete',
      current: 'Current step',
      waiting: 'Not started',
    },
    validation: {
      title: 'Plan checks',
      mandatory: 'Mandatory commitments',
      capacity: 'Capacity',
      resources: 'Shared resources',
      dependencies: 'Dependencies',
      cash: 'Cash',
      covered: '{{done}}/{{total}} covered',
      noConflict: 'No conflict found',
      conflict: 'Needs attention',
      valid: 'Valid',
      atRisk: 'At risk',
      safe: 'Safe',
      executive: 'Open executive summary',
    },
    assignment: { owner: 'Owner', contributor: 'Contributor' },
    contextual: {
      wantWork: 'I still want to execute this work',
      capacity: 'Try changing capacity',
      cash: 'Try changing starting cash',
    },
  },
  ja: {
    entry: {
      eyebrow: '業務起点の計画',
      title: '運営計画を作成',
      description: '会社の計画データを読み込むか、既存のサンプルデータで流れを確認します。人員や最終数値より先に業務を確認します。',
      create: '新しい計画を作成',
      sample: 'サンプルデータを使用',
    },
    planning: {
      eyebrow: 'ステップ1・計画データ',
      title: '計画データを作成・読込',
      description: '対応済みのNexaWorksスキーマに沿ったJSON、または変更されていないサンプルデータを使用します。',
      upload: '計画JSONファイルを読み込む',
      uploadHelp: '既存スキーマで検証します。読み込みだけでは分析や計画生成は行いません。',
      choose: 'JSONファイルを選択',
      sample: 'サンプルデータを使用',
      reviewing: '計画データを検証中…',
      loaded: '計画データを確認できます',
      sampleSource: '既存サンプルデータ',
      uploadedSource: 'アップロードした計画データ',
      horizon: '計画期間',
      workItems: '業務項目',
      people: '人員',
      capacity: '利用可能工数',
      commercial: '商談選択肢',
      resources: '共有リソース',
      effects: 'ポートフォリオ効果',
      startingCash: '開始時現金',
      buffer: '最低現金安全水準',
      reviewWork: '業務項目を確認',
      startOver: '最初からやり直す',
      invalid: '対応している計画データとして読み込めませんでした。',
    },
    work: {
      eyebrow: 'ステップ2–3・業務ポートフォリオ',
      title: '人員を割り当てる前に業務を確認',
      description: '提案を作る前に、約束、工数、期限、顧客、依存関係を理解します。',
      all: 'すべて', mandatory: '必須', commercial: '商談', other: 'その他',
      mandatoryLabel: '必須の約束', optionalLabel: '任意業務', hours: '必要工数', deadline: '期限', customer: '顧客', dependencies: '依存関係', none: 'なし',
      notAnalyzed: '未分析', analyze: 'ポートフォリオを分析', analyzing: 'ポートフォリオを分析中…',
      analysisReady: 'ポートフォリオ分析が完了しました',
      analysisExplain: '優先度は事業上の重要度です。実行順序ではありません。',
      dependencyExample: '{{work}}は重要ですが、先に前提業務を完了する必要があります。',
      priority: '優先度', veryHigh: '最優先', high: '高', medium: '中', low: '低',
      feasibility: '実行可能性', feasible: '実行可能', blocked: '前提業務の完了まで保留', infeasible: '現在の前提では実行不可', atRisk: 'リスクあり',
      keyReasons: '主な理由', rawEvidence: '分析根拠', generate: '推奨計画を生成', generating: '推奨計画を生成中…', planReady: '推奨計画を生成しました', openPlan: '実行計画を確認',
    },
    gate: {
      noDataTitle: '先に計画データが必要です', noDataBody: 'このステップを確認する前に計画を作成するかサンプルデータを読み込んでください。', goPlanning: '計画データへ',
      analysisTitle: '先に業務ポートフォリオを分析', analysisBody: '業務を確認し、明示的に分析してから計画を生成します。', goWork: '業務項目を確認',
      planTitle: '推奨計画はまだ生成されていません', planBody: '分析済みの業務から計画を生成してから、人員、資金、シナリオ、経営概要を確認します。', generatePlan: '推奨計画を生成',
      sampleOnlyTitle: 'シナリオは現在サンプル基準を使用します', sampleOnlyBody: 'アップロードデータは分離されています。既存シナリオ機能にはサンプルデータを使用してください。',
    },
    progress: { data: '計画データ', work: '業務確認', analysis: '分析', plan: '推奨計画', complete: '完了', current: '現在', waiting: '未開始' },
    validation: {
      title: '計画チェック', mandatory: '必須業務', capacity: '工数', resources: '共有リソース', dependencies: '依存関係', cash: '資金',
      covered: '{{done}}/{{total}} 対応', noConflict: '競合なし', conflict: '要確認', valid: '有効', atRisk: 'リスクあり', safe: '安全', executive: '経営概要を開く',
    },
    assignment: { owner: '責任者', contributor: '担当者' },
    contextual: { wantWork: 'この業務を実行したい', capacity: '工数を変更して試す', cash: '開始時現金を変更して試す' },
  },
  vi: {
    entry: {
      eyebrow: 'Lập kế hoạch từ công việc',
      title: 'Xây dựng kế hoạch vận hành',
      description: 'Nhập dữ liệu kế hoạch của doanh nghiệp hoặc dùng bộ dữ liệu mẫu hiện có để hiểu quy trình. Công việc được xem xét trước nhân sự, lịch và số liệu cuối.',
      create: 'Tạo kế hoạch mới',
      sample: 'Dùng dữ liệu mẫu',
    },
    planning: {
      eyebrow: 'Bước 1 · Dữ liệu kế hoạch',
      title: 'Tạo hoặc nạp dữ liệu kế hoạch',
      description: 'Dùng tệp JSON theo schema NexaWorks đang hỗ trợ, hoặc bắt đầu an toàn với bộ dữ liệu mẫu không thay đổi.',
      upload: 'Nạp tệp JSON kế hoạch',
      uploadHelp: 'Tệp được kiểm tra bằng schema hiện có. Nạp dữ liệu không tự phân tích hay tạo kế hoạch.',
      choose: 'Chọn tệp JSON',
      sample: 'Dùng dữ liệu mẫu',
      reviewing: 'Đang kiểm tra dữ liệu kế hoạch…',
      loaded: 'Dữ liệu kế hoạch đã sẵn sàng để xem',
      sampleSource: 'Bộ dữ liệu mẫu hiện có',
      uploadedSource: 'Bộ dữ liệu kế hoạch đã tải lên',
      horizon: 'Kỳ kế hoạch',
      workItems: 'Công việc',
      people: 'Nhân sự',
      capacity: 'Năng lực khả dụng',
      commercial: 'Phương án thương mại',
      resources: 'Nguồn lực dùng chung',
      effects: 'Ảnh hưởng danh mục',
      startingCash: 'Tiền mặt đầu kỳ',
      buffer: 'Mức tiền mặt an toàn tối thiểu',
      reviewWork: 'Xem công việc',
      startOver: 'Làm lại từ đầu',
      invalid: 'Không thể nạp tệp này dưới dạng dữ liệu kế hoạch được hỗ trợ.',
    },
    work: {
      eyebrow: 'Bước 2–3 · Danh mục công việc',
      title: 'Xem công việc trước khi phân công nhân sự',
      description: 'Hiểu cam kết, khối lượng, thời hạn, khách hàng và phụ thuộc trước khi yêu cầu hệ thống đề xuất.',
      all: 'Tất cả', mandatory: 'Bắt buộc', commercial: 'Thương mại', other: 'Công việc khác',
      mandatoryLabel: 'Cam kết bắt buộc', optionalLabel: 'Công việc tùy chọn', hours: 'Khối lượng yêu cầu', deadline: 'Thời hạn', customer: 'Khách hàng', dependencies: 'Phụ thuộc', none: 'Không có',
      notAnalyzed: 'Chưa phân tích', analyze: 'Phân tích danh mục', analyzing: 'Đang phân tích danh mục…',
      analysisReady: 'Đã có kết quả phân tích danh mục',
      analysisExplain: 'Mức ưu tiên thể hiện tầm quan trọng kinh doanh, không phải thứ tự thực hiện.',
      dependencyExample: '{{work}} có ưu tiên cao nhưng công việc tiên quyết phải hoàn thành trước.',
      priority: 'Mức ưu tiên', veryHigh: 'Rất cao', high: 'Cao', medium: 'Trung bình', low: 'Thấp',
      feasibility: 'Khả năng thực hiện', feasible: 'Có thể thực hiện', blocked: 'Bị chặn đến khi hoàn thành công việc tiên quyết', infeasible: 'Không thể thực hiện với giả định hiện tại', atRisk: 'Có rủi ro',
      keyReasons: 'Lý do chính', rawEvidence: 'Bằng chứng phân tích', generate: 'Tạo kế hoạch đề xuất', generating: 'Đang tạo kế hoạch đề xuất…', planReady: 'Đã tạo kế hoạch đề xuất', openPlan: 'Xem kế hoạch thực hiện',
    },
    gate: {
      noDataTitle: 'Cần có dữ liệu kế hoạch trước', noDataBody: 'Hãy tạo kế hoạch hoặc nạp dữ liệu mẫu trước khi xem bước này.', goPlanning: 'Đi tới Lập kế hoạch',
      analysisTitle: 'Hãy phân tích danh mục công việc trước', analysisBody: 'Xem các công việc và chủ động chạy phân tích trước khi tạo kế hoạch.', goWork: 'Xem công việc',
      planTitle: 'Chưa tạo kế hoạch đề xuất', planBody: 'Hãy tạo kế hoạch từ danh mục đã phân tích trước khi xem phân công, dòng tiền, kịch bản hoặc tổng quan quản trị.', generatePlan: 'Tạo kế hoạch đề xuất',
      sampleOnlyTitle: 'Kịch bản hiện dùng dữ liệu nền mẫu', sampleOnlyBody: 'Dữ liệu tải lên vẫn được cách ly. Hãy bắt đầu workflow dữ liệu mẫu để dùng bộ máy kịch bản hiện có.',
    },
    progress: { data: 'Dữ liệu kế hoạch', work: 'Xem công việc', analysis: 'Phân tích', plan: 'Kế hoạch đề xuất', complete: 'Hoàn tất', current: 'Bước hiện tại', waiting: 'Chưa bắt đầu' },
    validation: {
      title: 'Kiểm tra kế hoạch', mandatory: 'Cam kết bắt buộc', capacity: 'Năng lực', resources: 'Nguồn lực dùng chung', dependencies: 'Phụ thuộc', cash: 'Dòng tiền',
      covered: '{{done}}/{{total}} được bảo đảm', noConflict: 'Không có xung đột', conflict: 'Cần chú ý', valid: 'Hợp lệ', atRisk: 'Có rủi ro', safe: 'An toàn', executive: 'Mở tổng quan quản trị',
    },
    assignment: { owner: 'Người phụ trách chính', contributor: 'Thành viên thực hiện' },
    contextual: { wantWork: 'Tôi vẫn muốn thực hiện việc này', capacity: 'Thử thay đổi năng lực', cash: 'Thử thay đổi tiền mặt đầu kỳ' },
  },
} as const

export function workflowCopy(language?: string) {
  return copies[uiLanguage(language)]
}

export function localized(value: string | Record<string, string | null | undefined> | null | undefined, language?: string): string {
  if (!value) return ''
  if (typeof value === 'string') return value
  const lang = uiLanguage(language)
  return value[lang] || value.en || value.ja || value.vi || ''
}

export function template(value: string, values: Record<string, string | number>) {
  return Object.entries(values).reduce((text, [key, replacement]) => text.replaceAll(`{{${key}}}`, String(replacement)), value)
}
