"""Machine-readable enums for Phase 2F cash-flow simulation."""
from enum import Enum


class CashScenario(str, Enum):
    EXPECTED = "EXPECTED"
    DOWNSIDE = "DOWNSIDE"
    SUCCESS = "SUCCESS"


class CashDirection(str, Enum):
    INFLOW = "INFLOW"
    OUTFLOW = "OUTFLOW"


class CashEventType(str, Enum):
    FIXED_OUTFLOW = "FIXED_OUTFLOW"
    WORK_DIRECT_COST = "WORK_DIRECT_COST"
    COMMERCIAL_DELIVERY_COST = "COMMERCIAL_DELIVERY_COST"
    WORK_CASH_RECEIPT = "WORK_CASH_RECEIPT"
    COMMERCIAL_CASH_RECEIPT = "COMMERCIAL_CASH_RECEIPT"
    PORTFOLIO_CASH_INFLOW = "PORTFOLIO_CASH_INFLOW"
    LATE_PENALTY = "LATE_PENALTY"


class CashSourceType(str, Enum):
    COMPANY = "COMPANY"
    WORK_ITEM = "WORK_ITEM"
    COMMERCIAL_OPTION = "COMMERCIAL_OPTION"
    PORTFOLIO_EFFECT = "PORTFOLIO_EFFECT"


class ScenarioCashStatus(str, Enum):
    CASH_SAFE = "CASH_SAFE"
    BUFFER_BREACH = "BUFFER_BREACH"
    NEGATIVE_CASH = "NEGATIVE_CASH"


class OverallCashStatus(str, Enum):
    CASH_SAFE = "CASH_SAFE"
    CASH_AT_RISK = "CASH_AT_RISK"


class CashReasonCode(str, Enum):
    STARTING_CASH_LOADED = "STARTING_CASH_LOADED"
    FIXED_OUTFLOW_PRORATED = "FIXED_OUTFLOW_PRORATED"
    DIRECT_COST_PRORATED = "DIRECT_COST_PRORATED"
    CASH_RECEIPT_SCHEDULED = "CASH_RECEIPT_SCHEDULED"
    CASH_RECEIPT_OUTSIDE_HORIZON = "CASH_RECEIPT_OUTSIDE_HORIZON"
    EXPECTED_PROBABILISTIC_INFLOW = "EXPECTED_PROBABILISTIC_INFLOW"
    DOWNSIDE_PROBABILISTIC_INFLOW_ZERO = "DOWNSIDE_PROBABILISTIC_INFLOW_ZERO"
    MINIMUM_BUFFER_BREACH = "MINIMUM_BUFFER_BREACH"
    NEGATIVE_CASH = "NEGATIVE_CASH"
    LATE_PENALTY_APPLIED = "LATE_PENALTY_APPLIED"
    LATE_PENALTY_CASH_SEMANTICS_UNSUPPORTED = "LATE_PENALTY_CASH_SEMANTICS_UNSUPPORTED"
    CASH_TIMING_ASSUMPTION_USED = "CASH_TIMING_ASSUMPTION_USED"
    CASH_TIMING_UNAVAILABLE = "CASH_TIMING_UNAVAILABLE"
    UNCOMMITTED_WORK_REVENUE_EXCLUDED = "UNCOMMITTED_WORK_REVENUE_EXCLUDED"
    COMMERCIAL_COST_CONDITIONAL_ON_WIN = "COMMERCIAL_COST_CONDITIONAL_ON_WIN"
    DELAYED_ACTION_EXCLUDED = "DELAYED_ACTION_EXCLUDED"
    NO_BID_EXCLUDED = "NO_BID_EXCLUDED"
