import { useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { scenarioApi } from '../api/endpoints'
import type { CashFlowResult, CashScenarioResult, ScenarioRun } from '../api/types'
import { ConclusionCard, ManagementSection, ManagerError, ManagerLoading, ManagerStatus, Money, PageIntro, RunContext } from '../components/business/BusinessUI'
import { RunContextNav } from '../components/run/RunContextNav'
import { managerCopy } from '../utils/managerCopy'
import { buildCashAdjustmentAdvice } from '../utils/cashAdjustments'
import { formatDate, formatMoneyCompact, scenarioLabel, statusTone } from '../utils/presentation'
import { useWorkflow } from '../workflow/WorkflowContext'
import { WorkflowGate, WorkflowProgress } from '../workflow/WorkflowUI'
import { localized } from '../workflow/copy'

const scenarioOrder = ['EXPECTED', 'DOWNSIDE', 'SUCCESS']
const colors: Record<string, string> = { EXPECTED: '#2563eb', DOWNSIDE: '#b45309', SUCCESS: '#07836f' }

function CashChart({ cash }: { cash: CashFlowResult }) {
  const { i18n } = useTranslation(); const c = managerCopy(i18n.resolvedLanguage).cash; const series = scenarioOrder.map((name) => cash.scenarios[name]).filter(Boolean); const values = series.flatMap((item) => item.timeline.map((day) => day.closing_cash_jpy)).concat([cash.minimum_buffer_jpy, 0]); const max = Math.max(...values); const min = Math.min(...values); const range = Math.max(1, max - min); const width = 900; const height = 310; const left = 72; const right = 24; const top = 20; const bottom = 38; const y = (value: number) => top + ((max - value) / range) * (height - top - bottom); const x = (index: number, count: number) => left + (index / Math.max(1, count - 1)) * (width - left - right)
  return <div className='cash-chart-wrap manager-cash-chart' data-testid='cash-chart'><div className='chart-legend'>{series.map((item) => <span key={item.scenario}><i style={{ background: colors[item.scenario] }} />{scenarioLabel(item.scenario, i18n.resolvedLanguage)}</span>)}<span><i className='safe-zone-key' />{c.safeZone}</span><span><i className='below-zone-key' />{c.belowBuffer}</span><span><i className='negative-zone-key' />{c.negative}</span></div><svg viewBox={`0 0 ${width} ${height}`} role='img' aria-label={c.chartLabel}><rect x={left} y={top} width={width - left - right} height={Math.max(0, y(cash.minimum_buffer_jpy) - top)} className='cash-chart__safe-zone' /><rect x={left} y={y(cash.minimum_buffer_jpy)} width={width - left - right} height={Math.max(0, y(0) - y(cash.minimum_buffer_jpy))} className='cash-chart__warning-zone' />{min < 0 && <rect x={left} y={y(0)} width={width - left - right} height={height - bottom - y(0)} className='cash-chart__negative-zone' />}<line x1={left} x2={width - right} y1={y(cash.minimum_buffer_jpy)} y2={y(cash.minimum_buffer_jpy)} className='cash-chart__buffer' /><line x1={left} x2={width - right} y1={y(0)} y2={y(0)} className='cash-chart__zero' />{series.map((item) => <polyline key={item.scenario} fill='none' stroke={colors[item.scenario]} strokeWidth='3' points={item.timeline.map((day, index) => `${x(index, item.timeline.length)},${y(day.closing_cash_jpy)}`).join(' ')} />)}<text x='4' y={y(max) + 4}>{formatMoneyCompact(max, 'en')}</text><text x='4' y={y(min) + 4}>{formatMoneyCompact(min, 'en')}</text><text x={left} y={height - 8}>{series[0]?.timeline[0]?.date ?? ''}</text><text textAnchor='end' x={width - right} y={height - 8}>{series[0]?.timeline.at(-1)?.date ?? ''}</text></svg></div>
}

function ScenarioCard({ item }: { item: CashScenarioResult }) { const { i18n } = useTranslation(); const c = managerCopy(i18n.resolvedLanguage).cash; const locale = i18n.resolvedLanguage ?? 'en'; return <article className={`cash-business-card cash-business-card--${statusTone(item.status)}`}><div className='cash-business-card__heading'><h3>{scenarioLabel(item.scenario, i18n.resolvedLanguage)}</h3><ManagerStatus status={item.status} /></div><strong className='cash-business-card__value'><Money value={item.ending_cash_jpy} compact={false} /></strong><dl><div><dt>{c.minimum}</dt><dd><Money value={item.minimum_cash_jpy} /> <small>{formatDate(item.minimum_cash_date, locale)}</small></dd></div><div><dt>{c.daysBelow}</dt><dd>{item.days_below_buffer}</dd></div><div><dt>{c.cashIn}</dt><dd><Money value={item.total_cash_in_jpy} /></dd></div><div><dt>{c.cashOut}</dt><dd><Money value={item.total_cash_out_jpy} /></dd></div></dl></article> }

export function CashFlowPage() {
  const { i18n } = useTranslation(); const c = managerCopy(i18n.resolvedLanguage).cash; const locale = i18n.resolvedLanguage ?? 'en'; const [params] = useSearchParams(); const runId = params.get('run_id'); const workflow = useWorkflow()
  const [run, setRun] = useState<ScenarioRun | null>(null); const [loading, setLoading] = useState(Boolean(runId)); const [error, setError] = useState(false); const [reloadKey, setReloadKey] = useState(0); const [activeScenario, setActiveScenario] = useState('EXPECTED')
  useEffect(() => { if (!runId) { setLoading(false); return } let current = true; setLoading(true); setError(false); void scenarioApi.getRun(runId).then((value) => { if (current) { setRun(value); setLoading(false) } }).catch(() => { if (current) { setError(true); setLoading(false) } }); return () => { current = false } }, [runId, reloadKey])
  const activeWorkflowRun = workflow.generation && workflow.catalog ? {
    run_id: 'ACTIVE-PLAN', scenario_id: workflow.catalog.summary.dataset_id,
    timestamp: workflow.generatedAt ?? new Date().toISOString(), effective_input: {}, assumptions: {},
    status: 'COMPLETED', error: null, ...workflow.generation,
  } as unknown as ScenarioRun : null
  const displayRun = runId ? run : activeWorkflowRun
  const available = useMemo(() => displayRun ? scenarioOrder.filter((name) => displayRun.cash_flow.scenarios[name]) : [], [displayRun])
  useEffect(() => { if (available.length && !available.includes(activeScenario)) setActiveScenario(available[0]) }, [available, activeScenario])
  if (runId && loading) return <ManagerLoading />
  if (runId && error) return <ManagerError onRetry={() => setReloadKey((value) => value + 1)} />
  if (!runId && !workflow.catalog) return <WorkflowGate kind='data' />
  if (!runId && !workflow.analysis) return <WorkflowGate kind='analysis' />
  if (!runId && !workflow.generation) return <WorkflowGate kind='plan' />
  if (!displayRun || displayRun.status === 'FAILED') return <WorkflowGate kind='plan' />
  const cash = displayRun.cash_flow; const expected = cash.scenarios.EXPECTED ?? cash.scenarios[available[0]]; const downside = cash.scenarios.DOWNSIDE ?? expected; const firstUnsafe = scenarioOrder.map((name) => cash.scenarios[name]?.first_buffer_breach_date).filter(Boolean).sort()[0]; const active = cash.scenarios[activeScenario]; const unsafe = cash.overall_status !== 'CASH_SAFE'
  const advice = workflow.catalog ? buildCashAdjustmentAdvice(cash, displayRun.plan, workflow.catalog) : null
  const scenarioLink = (values: Record<string, string | number>) => {
    const query = new URLSearchParams({ focus: 'cash', ...Object.fromEntries(Object.entries(values).map(([key, value]) => [key, String(value)])) })
    return `/scenarios?${query.toString()}`
  }
  return <div>{!runId && <WorkflowProgress status='PLAN_GENERATED' />}<RunContext runId={displayRun.run_id} timestamp={displayRun.timestamp} scenarioName={displayRun.scenario_id} />{runId && <RunContextNav runId={displayRun.run_id} />}<PageIntro eyebrow={c.eyebrow} title={c.title} description={c.description} /><ConclusionCard eyebrow={c.conclusion} title={unsafe ? c.unsafe : c.safe} tone={statusTone(cash.overall_status)} status={cash.overall_status} evidence={<div className='cash-conclusion-metrics'><span>{c.expectedEnding}<strong><Money value={expected?.ending_cash_jpy} compact={false} /></strong></span><span>{c.firstUnsafe}<strong>{formatDate(firstUnsafe, locale)}</strong></span></div>} />
    <ManagementSection title={c.conclusion}><div className='cash-kpi-grid'><article><span>{c.starting}</span><strong><Money value={cash.starting_cash_jpy} /></strong></article><article><span>{c.buffer}</span><strong><Money value={cash.minimum_buffer_jpy} /></strong></article><article className={expected?.ending_cash_jpy < 0 ? 'kpi-critical' : ''}><span>{c.expectedEnding}</span><strong><Money value={expected?.ending_cash_jpy} /></strong></article><article className={downside?.ending_cash_jpy < 0 ? 'kpi-critical' : ''}><span>{c.worstEnding}</span><strong><Money value={downside?.ending_cash_jpy} /></strong></article><article><span>{c.firstUnsafe}</span><strong>{formatDate(firstUnsafe, locale)}</strong></article></div><div className='cash-business-grid'>{available.map((name) => <ScenarioCard key={name} item={cash.scenarios[name]} />)}</div></ManagementSection>
    {!runId && advice && <ManagementSection title={c.adjustments} description={c.adjustmentExplain}><div className='cash-adjustment-summary'><article className={advice.gapToAvoidNegativeJpy > 0 ? 'kpi-critical' : ''}><span>{c.gapToZero}</span><strong><Money value={advice.gapToAvoidNegativeJpy} compact={false} /></strong></article><article><span>{c.gapToBuffer}</span><strong><Money value={advice.gapToSafetyBufferJpy} compact={false} /></strong></article></div>{advice.band === 'SAFE' ? <p className='liquidity-safe-message'>{c.noAdjustment}</p> : <div className='adjustment-card-grid'>
      {advice.deferrals[0] && <article className='adjustment-card'><span className='eyebrow'>{c.deferFirst}</span><h3>{localized(advice.deferrals[0].title, i18n.resolvedLanguage) || advice.deferrals[0].workItemId}</h3><small>{advice.deferrals[0].workItemId}</small><dl><div><dt>{c.relief}</dt><dd><Money value={advice.deferrals[0].liquidityReliefJpy} compact={false} /></dd></div><div><dt>{c.projectedEnding}</dt><dd><Money value={advice.deferrals[0].projectedEndingCashJpy} compact={false} /></dd></div></dl><p>{advice.deferrals[0].reachesSafetyBuffer ? c.reachesSafety : advice.deferrals[0].avoidsNegativeCash ? c.stillRisky : c.doesNotFix}</p><Link className='button button--secondary' to={scenarioLink({ name: `${c.deferFirst}: ${advice.deferrals[0].workItemId}`, defer_work: advice.deferrals[0].workItemId })}>{c.tryOption}</Link></article>}
      {advice.deferralBundle && advice.deferrals.length > 1 && <article className='adjustment-card'><span className='eyebrow'>{c.deferBundle}</span><h3>{advice.deferrals.map((item) => item.workItemId).join(', ')}</h3><dl><div><dt>{c.relief}</dt><dd><Money value={advice.deferralBundle.liquidityReliefJpy} compact={false} /></dd></div><div><dt>{c.projectedEnding}</dt><dd><Money value={advice.deferralBundle.projectedEndingCashJpy} compact={false} /></dd></div></dl><p>{advice.deferralBundle.reachesSafetyBuffer ? c.reachesSafety : advice.deferralBundle.avoidsNegativeCash ? c.stillRisky : c.doesNotFix}</p><Link className='button button--secondary' to={scenarioLink({ name: c.deferBundle, defer_work: advice.deferrals.map((item) => item.workItemId).join(',') })}>{c.tryOption}</Link></article>}
      <article className='adjustment-card'><span className='eyebrow'>{c.funding}</span><h3><Money value={advice.gapToSafetyBufferJpy} compact={false} /></h3><p>{c.fundingExplain}</p><Link className='button button--secondary' to={scenarioLink({ name: c.funding, starting_cash: advice.requiredStartingCashJpy })}>{c.tryOption}</Link></article>
      {advice.receiptCandidates[0] && <article className='adjustment-card'><span className='eyebrow'>{c.earlyReceipt}</span><h3>{advice.receiptCandidates[0].workItemId} · <Money value={advice.receiptCandidates[0].amountJpy} compact={false} /></h3><p>{c.earlyReceiptExplain}</p><Link className='button button--secondary' to={scenarioLink({ name: `${c.earlyReceipt}: ${advice.receiptCandidates[0].workItemId}`, receipt_work: advice.receiptCandidates[0].workItemId, cash_in_days: 0 })}>{c.tryOption}</Link></article>}
      {advice.deferralBundle && advice.residualFundingAfterDeferralsJpy > 0 && <article className='adjustment-card adjustment-card--combined'><span className='eyebrow'>{c.combination}</span><h3>{advice.deferrals.map((item) => item.workItemId).join(', ')}</h3><dl><div><dt>{c.relief}</dt><dd><Money value={advice.deferralBundle.liquidityReliefJpy} /></dd></div><div><dt>{c.residualFunding}</dt><dd><Money value={advice.residualFundingAfterDeferralsJpy} /></dd></div></dl><Link className='button' to={scenarioLink({ name: c.combination, defer_work: advice.deferrals.map((item) => item.workItemId).join(','), cash_addition: advice.residualFundingAfterDeferralsJpy })}>{c.tryOption}</Link></article>}
    </div>}<p className='advisory-note'>{c.advisoryOnly}</p></ManagementSection>}
    <ManagementSection title={c.chart}><CashChart cash={cash} /></ManagementSection>
    {cash.future_events.length > 0 && <ManagementSection title={c.future} description={c.futureExplain}><div className='liquidity-insight'><span aria-hidden='true'>!</span><p>{c.futureExplain}</p></div><div className='manager-table-wrap'><table className='manager-table'><thead><tr><th>{c.source}</th><th>{c.amount}</th><th>{c.receipt}</th><th>{c.scenario}</th></tr></thead><tbody>{cash.future_events.map((event) => <tr key={event.event_id}><td><strong>{event.source_id}</strong><small>{event.event_type}</small></td><td><Money value={event.amount_jpy} compact={false} /></td><td>{formatDate(event.date, locale)}</td><td>{scenarioLabel(event.scenario, i18n.resolvedLanguage)}</td></tr>)}</tbody></table></div></ManagementSection>}
    <details className='audit-details audit-details--page'><summary>{c.timeline}</summary><div className='inline-select'><label><span>{c.scenario}</span><select value={activeScenario} onChange={(event) => setActiveScenario(event.target.value)}>{available.map((name) => <option key={name} value={name}>{scenarioLabel(name, i18n.resolvedLanguage)}</option>)}</select></label></div>{active && <div className='data-table-wrap'><table className='data-table cash-ledger'><thead><tr><th>{c.date}</th><th>{c.opening}</th><th>{c.cashIn}</th><th>{c.cashOut}</th><th>{c.closing}</th><th>{c.markers}</th></tr></thead><tbody>{active.timeline.map((day) => <tr key={day.date} className={day.negative_cash ? 'cash-row--negative' : day.buffer_breach ? 'cash-row--breach' : ''}><td>{formatDate(day.date, locale)}</td><td><Money value={day.opening_cash_jpy} compact={false} /></td><td><Money value={day.cash_in_jpy} compact={false} /></td><td><Money value={day.cash_out_jpy} compact={false} /></td><td><Money value={day.closing_cash_jpy} compact={false} /></td><td>{day.negative_cash ? <span className='marker marker--negative'>{c.negative}</span> : day.buffer_breach ? <span className='marker marker--breach'>{c.belowBuffer}</span> : c.safeZone}</td></tr>)}</tbody></table></div>}</details>
  </div>
}
