"""Machine-readable enums for the deterministic Phase 2E planner."""
from enum import Enum


class PlanStatus(str, Enum):
    FEASIBLE = "FEASIBLE"
    PARTIAL = "PARTIAL"
    INFEASIBLE = "INFEASIBLE"


class DecisionType(str, Enum):
    DO = "DO"
    DELAY = "DELAY"
    SELECT_OPTION = "SELECT_OPTION"
    NO_BID = "NO_BID"
    MANDATORY_INFEASIBLE = "MANDATORY_INFEASIBLE"
    AT_RISK = "AT_RISK"
    ENABLING_PREREQUISITE = "ENABLING_PREREQUISITE"


class AllocationType(str, Enum):
    WORK = "WORK"
    SCHEDULED_BASE_EFFORT = "SCHEDULED_BASE_EFFORT"
    RESERVED_DELIVERY = "RESERVED_DELIVERY"


class PlannerReasonCode(str, Enum):
    MANDATORY_SELECTED = "MANDATORY_SELECTED"
    MANDATORY_INFEASIBLE = "MANDATORY_INFEASIBLE"
    PREREQUISITE_SELECTED = "PREREQUISITE_SELECTED"
    PREREQUISITE_COMPLETED = "PREREQUISITE_COMPLETED"
    OPTION_UNLOCKED_IN_PLAN = "OPTION_UNLOCKED_IN_PLAN"
    SELECTED_BY_BUSINESS_VALUE = "SELECTED_BY_BUSINESS_VALUE"
    DELAYED_CAPACITY_LIMIT = "DELAYED_CAPACITY_LIMIT"
    DELAYED_RESOURCE_CONFLICT = "DELAYED_RESOURCE_CONFLICT"
    DELAYED_PREREQUISITE_NOT_SCHEDULABLE = "DELAYED_PREREQUISITE_NOT_SCHEDULABLE"
    DELAYED_HARD_CONSTRAINT = "DELAYED_HARD_CONSTRAINT"
    NO_BID_NO_FEASIBLE_OPTION = "NO_BID_NO_FEASIBLE_OPTION"
    NO_BID_CAPACITY_CONSTRAINT = "NO_BID_CAPACITY_CONSTRAINT"
    PERSON_CAPACITY_EXCEEDED = "PERSON_CAPACITY_EXCEEDED"
    RESOURCE_CONFLICT = "RESOURCE_CONFLICT"
    DEPENDENCY_ORDER_ENFORCED = "DEPENDENCY_ORDER_ENFORCED"
    DEPENDENCY_CYCLE_DETECTED = "DEPENDENCY_CYCLE_DETECTED"
    SCHEDULED_AFTER_DUE_DATE = "SCHEDULED_AFTER_DUE_DATE"
    DELIVERY_CAPACITY_RESERVED = "DELIVERY_CAPACITY_RESERVED"
    SALES_OPPORTUNITY_EXPIRED = "SALES_OPPORTUNITY_EXPIRED"
    MISSING_SKILL_COVERAGE = "MISSING_SKILL_COVERAGE"
    MISSING_LANGUAGE_COVERAGE = "MISSING_LANGUAGE_COVERAGE"
    INVALID_REFERENCE = "INVALID_REFERENCE"
    MUTUALLY_EXCLUSIVE_ENFORCED = "MUTUALLY_EXCLUSIVE_ENFORCED"
    DAILY_CAPACITY_POLICY_APPLIED = "DAILY_CAPACITY_POLICY_APPLIED"
    PORTFOLIO_EFFECT_APPLIED = "PORTFOLIO_EFFECT_APPLIED"
